 $(document).ready(function(){$("img#closed").click(function(){$("#btm_banner").hide(90)})}); 
 /<![CDATA[/var a=navigator,b="userAgent",c="indexOf",f="&m=1",g="(^|&)m=",h="?",i="?m=1";function j(){var m=window.location.href,l=m.split(h);switch(l.length){case 1:return m+i;case 2:return 0<=l[1].search(g)?null:m+f;default:return null}}if(-1!=a[b][c]("Mobile")&&-1!=a[b][c]("WebKit")&&-1==a[b][c]("iPad")||-1!=a[b][c]("Opera Mini")||-1!=a[b][c]("IEMobile")){var k=j();k&&window.location.replace(k)}/]]>/  if(window.jstiming){window.jstiming.load.tick("headEnd")}; 
 
        function myfunction() {
     document.getElementById('teaser2').style.display = 'none';
 }
var delay = 2000;

     
 
var d = new Date();
var h = d.getHours();
if (h%2==0) {
    text = "<style>@media screen and (min-width: 721px){#teaser2{width:auto;height:auto;text-align:left;z-index:999999 !important;display:none;position:fixed;bottom:0px;left:0px;}}@media screen and (max-width: 720px){#teaser2{width:auto;height:auto;text-align:left;z-index:999999 !important;display:scroll;position:fixed;bottom:0px;left:0px;}}.close{position:absolute;z-index:999999 !important;top:4px;left:4px;background:#fff;font:bold 16px Arial, Sans-Serif;text-decoration:none;line-height:10px;width:10px;text-align:center;color:#111;border:2px solid #333;-webkit-box-shadow:0px 1px 2px rgba(0,0,0,0.4);-moz-box-shadow:0px 1px 2px rgba(0,0,0,0.4);box-shadow:0px 1px 2px rgba(0,0,0,0.4);-webkit-border-radius:22px;-moz-border-radius:22px;border-radius:22px;cursor:pointer;}#box-message{position:fixed !important;z-index:999999 !important;position:absolute;top:370px;left:17%;margin:0px 0px 0px 0px;width:285px;height:260px;padding:16px;background:#fff;font:normal Dosis, Georgia, Serif;color:#111;border:2px solid #333;-webkit-box-shadow:0px 1px 2px rgba(0,0,0,0.4);-moz-box-shadow:0px 1px 2px rgba(0,0,0,0.4);box-shadow:0px 1px 2px rgba(0,0,0,0.4);-webkit-border-radius:10px;-moz-border-radius:10px;border-radius:10px;}#box-message a.close{position:absolute;top:-12px;left:-14px;background:#fff;font:bold 16px Arial, Sans-Serif;text-decoration:none;line-height:10px;width:10px;text-align:center;color:#111;border:2px solid #333;-webkit-box-shadow:0px 1px 2px rgba(0,0,0,0.4);-moz-box-shadow:0px 1px 2px rgba(0,0,0,0.4);box-shadow:0px 1px 2px rgba(0,0,0,0.4);-webkit-border-radius:22px;-moz-border-radius:22px;border-radius:22px;cursor:pointer;</style><div id='teaser2'style='width:autopx;height:0;textalign:left;display:scroll;position:fixed;top:180px;left:15%'><a href='#' id='close-teaser' onclick='setTimeout(myfunction, delay);'><center><font color='red'><b><center class='close'>&#215;</center></b></font></center></a><div id='box-message' i-amphtml-fixedid='F0' style='top: 200px;'><b><center>= [ FOLLOW & CLOSE (X) ] To Read Article =</center></b><br /><center><p></p></center><code style='color:#000;cursor:pointer;float:right;margin-right:-20px;margin-top:-20px'><center><iframe  height='200' scrolling='no' src='//mil-04.blogspot.com' width='315'></iframe></center></code></div></div>";

} else {

    text = "<style>@media screen and (min-width: 721px){#teaser2{width:auto;z-index:999999 !important;height:auto;text-align:left;display:none;position:fixed;bottom:0px;left:0px;}}@media screen and (max-width: 720px){#teaser2{width:auto;z-index:999999 !important;height:auto;text-align:left;display:scroll;position:fixed;bottom:0px;left:0px;}}.close{position:absolute;z-index:999999 !important;top:4px;left:4px;background:#fff;font:bold 16px Arial, Sans-Serif;text-decoration:none;line-height:10px;width:10px;text-align:center;color:#111;border:2px solid #333;-webkit-box-shadow:0px 1px 2px rgba(0,0,0,0.4);-moz-box-shadow:0px 1px 2px rgba(0,0,0,0.4);box-shadow:0px 1px 2px rgba(0,0,0,0.4);-webkit-border-radius:22px;-moz-border-radius:22px;border-radius:22px;cursor:pointer;}#box-message{position:fixed !important;z-index:999999 !important;position:absolute;top:370px;left:17%;margin:0px 0px 0px 0px;width:285px;height:260px;padding:16px;background:#fff;font:normal Dosis, Georgia, Serif;color:#111;border:2px solid #333;-webkit-box-shadow:0px 1px 2px rgba(0,0,0,0.4);-moz-box-shadow:0px 1px 2px rgba(0,0,0,0.4);box-shadow:0px 1px 2px rgba(0,0,0,0.4);-webkit-border-radius:10px;-moz-border-radius:10px;border-radius:10px;}#box-message a.close{position:absolute;z-index:999999 !important;top:-12px;left:-14px;background:#fff;font:bold 16px Arial, Sans-Serif;text-decoration:none;line-height:10px;width:10px;text-align:center;color:#111;border:2px solid #333;-webkit-box-shadow:0px 1px 2px rgba(0,0,0,0.4);-moz-box-shadow:0px 1px 2px rgba(0,0,0,0.4);box-shadow:0px 1px 2px rgba(0,0,0,0.4);-webkit-border-radius:22px;-moz-border-radius:22px;border-radius:22px;cursor:pointer;</style><div id='teaser2'style='width:autopx;height:0;textalign:left;display:scroll;position:fixed;top:180px;left:15%'><a href='#' id='close-teaser' onclick='setTimeout(myfunction, delay);'><center><font color='red'><b><center class='close'>&#215;</center></b></font></center></a><div id='box-message' i-amphtml-fixedid='F0' style='top: 200px;'><b><center>= [ FOLLOW & CLOSE (X) ] To Read Article =</center></b><br /><center><p></p></center><code style='color:#000;cursor:pointer;float:right;margin-right:-20px;margin-top:-20px'><center><iframe  height='200' scrolling='no' src='//mil-04.blogspot.com' width='315'></iframe></center></code></div></div>";
}
document.getElementById("demo").innerHTML = text;
 
